version: "3"

services:
  proxy:
    container_name: stats_proxy
    image: nginx:alpine
    depends_on:
      - matomo
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${PORT}
      LETSENCRYPT_HOST: ${URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - matomo:/var/www/html:ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${PORT}:80
    networks:
      - default
      - nginx-proxy
    restart: always

  matomo:
    container_name: stats_matomo
    image: matomo:fpm-alpine
    depends_on:
      - mysql
    environment:
      MATOMO_DATABASE_HOST: mysql
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: ${DATABASE_NAME}_
      MATOMO_DATABASE_DBNAME: ${DATABASE_NAME}
      MATOMO_DATABASE_USERNAME: ${DATABASE_USER}
      MATOMO_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 80
    volumes:
      #      - ./config:/var/www/html/config:rw
      #      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    networks:
      - default
    restart: always

  mysql:
    container_name: stats_db
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default
    restart: always

volumes:
  mysql:
  matomo:

networks:
  nginx-proxy:
    external: true
