version: "3"

services:
  app:
    image: matomo:fpm-alpine
    depends_on:
      - mysql
    expose:
      - 80
    environment:
      MATOMO_DATABASE_HOST: mysql
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: ${DATABASE_NAME}_
      MATOMO_DATABASE_DBNAME: ${DATABASE_NAME}
      MATOMO_DATABASE_USERNAME: ${DATABASE_USER}
      MATOMO_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      #      - ./config:/var/www/html/config:rw
      #      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    restart: always

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  web:
    image: nginx:alpine
    volumes:
      - matomo:/var/www/html:ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${PORT}:80
    restart: always

volumes:
  mysql:
  matomo:
